# Travis CI build file.

# whitelist (branches that should be built)
branches:
  only:
    - master
    - /^issue.*$/

# the matrix of builds should cover each combination of Swift version
# and platform that is supported. The version of Swift used is specified
# by .swift-version, unless SWIFT_SNAPSHOT is specified.
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=swift:5.0.1-xenial
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=swift:5.0.1 SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT
    - os: osx
      osx_image: xcode10.2
      sudo: required
    - os: osx
      osx_image: xcode10.2
      sudo: required
      env: SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
